#:import Factory kivy.factory.Factory


<Label>:
    font_name: "fonts/NanumGothic.ttf"


<Button>:
    font_name: "fonts/NanumGothic.ttf"
    font_size: 22


<MenuScreen>:

    GridLayout:
        cols: 2
        spacing: 20
        padding: 20

        Button:
            text: "김치찌개\n8,000원"

        Button:
            text: "불고기\n10,000원"

        Button:
            text: "라면\n5,000원"

        Button:
            text: "음료\n2,000원"